const mongoose=require('mongoose');
const Schema=mongoose.Schema;

const stockDetailsSchema=new Schema({
    shortName:{
        type:String
    },
    fullName:{
        type:String
    },
    crrPrice:{
        type:Number
    },
    changed:{
        type:Number
    },
    perChanged:{
        type:Number
    },
    overView:{
        daysOpen:{
            type:Number
        },
        daysLow:{
            type:Number
        },
        daysHigh:{
            type:Number
        },
        previousClose:{
            type:Number
        },
        bestBid:{
            type:Number
        },
        bestAsk:{
            type:Number
        },
        volume:{
            type:Number
        },
        marketCap:{
            type:Number
        }
    },
    keyRatios:{
        eps:{
            type:Number
        },
        pe:{
            type:Number
        },
        pbv:{
            type:Number
        },
        roe:{
            type:Number
        },
        debt:{
            type:Number
        },
        netMargin:{
            type:Number
        },
        cagrSales:{
            type:Number
        },
        cagrProfit:{
            type:Number
        }
    },
    profitLoss:[{
        sales:{
            type:Number
        },
        directExpendiature:{
            type:Number
        },
        grossProfit:{
            type:Number
        },
        operatingProfit:{
            type:Number
        },
        otherIncome:{
            type:Number
        },
        interest:{
            type:Number
        },
        depreciation:{
            type:Number
        },
        profitBeforeTax:{
            type:Number
        },
        profitAfterTax:{
            type:Number
        },
        tax:{
            type:Number
        },
        eps:{
            type:Number
        },
        dividend:{
            type:Number
        }
    }],
    bse:{type:Number},
    nse:{type:Number},
    isin:{type:String},  
    compDet:{type:String},
    chairmain:{type:String},
    ceo:{type:String},
    coo:{type:String},
    indeDir:{type:String},
    nonIndeDir:{type:String},
    nonIndeDir1:{type:String},
    nonIndeDir2:{type:String},
    nonIndeDir3:{type:String},
    nonIndeDir4:{type:String},
})

module.exports=mongoose.model('stockDetail',stockDetailsSchema)