console.log('Hello world')
const calc=require('./calc')
const file=require('./FileHandling/File')
// // console.log(name(2,3))
console.log(calc.name)
// console.log(calc.add(3,4))
// calc.addUser('Perin')
// file.WriteDataToFile('Hello From Node....')
// file.WriteDataToFileDel('hello From node')
// file.readDataFromFile()
// // file.DelFile()
// file.createFile()

// file.CreateFolder()
// file.writejson()
// file.readDataFromJson()
// file.RenameFile()
